### Schema
CREATE DATABASE burgers_db;
USE burgers_db;

CREATE TABLE Food
(
	id int NOT NULL AUTO_INCREMENT,
	food_name varchar(255) NOT NULL,
	devoured TEXT NOT NULL,
	date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);
